/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.11.0")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.11.0")
}

group = "com.yit"
version = "1.0-SNAPSHOT"
description = "exp2"

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.register<JavaExec>("run") {
    mainClass.set("com.yit.demo.App")
    classpath = sourceSets["main"].runtimeClasspath
}
